services:

  postgres:
    image: postgres:17
    container_name: postgres-lab
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - infra-net


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-lab
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

    ports:
      - "8080:80"

    networks:
      - infra-net


  nginx:
    image: nginx:latest
    container_name: nginx-lab
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    networks:
      - infra-net


volumes:
  postgres_data:


networks:
  infra-net:
